# Generated by Django 5.2.4 on 2025-08-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='themes/backgrounds/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='font_family',
            field=models.CharField(default='Arial, sans-serif', max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='primary_color',
            field=models.CharField(default='#28a745', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='secondary_color',
            field=models.CharField(default='#1c7a34', max_length=7),
        ),
    ]
